# Generated by Django 5.1.2 on 2025-12-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="level",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="customuser",
            name="xp",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
