# Generated by Django 5.1.2 on 2026-01-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_level_customuser_xp"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="timezone",
            field=models.CharField(default="Europe/Istanbul", max_length=50),
        ),
    ]
