# Generated by Django 5.1.2 on 2026-01-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="points",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
