# Generated by Django 5.1.2 on 2026-05-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_reminder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("INFO", "Info"),
                    ("SUCCESS", "Success"),
                    ("WARNING", "Warning"),
                    ("CHECK", "Check"),
                    ("STREAK", "Streak"),
                    ("REMINDER", "Reminder"),
                ],
                default="INFO",
                max_length=20,
            ),
        ),
    ]
