# Generated by Django 5.1.2 on 2026-05-30 14:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_reminder_habit_reminder_last_sent_date_devicetoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_private",
            field=models.BooleanField(
                default=False,
                help_text="Private profiles hide habits/stats from non-friends",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="message_privacy",
            field=models.CharField(
                choices=[
                    ("everyone", "Everyone"),
                    ("friends", "Friends only"),
                    ("nobody", "Nobody"),
                ],
                default="everyone",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="region",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Country/city for regional leaderboards",
                max_length=80,
            ),
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blocked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blocker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocking",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("blocker", "blocked")},
            },
        ),
    ]
