# Generated by Django 5.1.2 on 2026-05-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_customuser_is_private_customuser_message_privacy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar_config",
            field=models.TextField(blank=True, default=""),
        ),
    ]
