# Generated by Django 5.1.2 on 2026-05-30 16:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_customuser_avatar_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvatarModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=80)),
                ("emoji", models.CharField(blank=True, default="", max_length=8)),
                (
                    "glb",
                    models.FileField(
                        blank=True, null=True, upload_to="models/avatars/"
                    ),
                ),
                (
                    "glb_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="External GLB URL (alternative to uploaded file)",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="models/avatar_thumbs/"
                    ),
                ),
                (
                    "scale",
                    models.FloatField(
                        default=1.0, help_text="Render scale hint for the RN viewer"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
    ]
