# Generated by Django 5.1.2 on 2026-06-10 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_purchase"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read"], name="users_notif_user_id_1be17e_idx"
            ),
        ),
    ]
