# Generated by Django 5.1.2 on 2026-06-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_notification_users_notif_user_id_1be17e_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="ai_checks_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="ai_checks_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
