# Generated by Django 5.1.2 on 2026-06-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_customuser_ai_checks_count_customuser_ai_checks_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
