# Generated by Django 5.1.2 on 2026-01-24 10:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChallengeTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "predefined_habit_name",
                    models.CharField(
                        help_text="The exact habit name user must use (e.g., 'Running')",
                        max_length=100,
                    ),
                ),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[("SOLO", "Solo"), ("DUO", "Duo (Friend)")],
                        default="SOLO",
                        max_length=10,
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(help_text="Days required to complete"),
                ),
                ("reward_xp", models.PositiveIntegerField(default=100)),
                ("reward_points", models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="items/")),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Common"),
                            ("rare", "Rare"),
                            ("epic", "Epic"),
                            ("legendary", "Legendary"),
                        ],
                        default="common",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("habit_name", models.CharField(editable=False, max_length=100)),
                ("current_streak", models.PositiveIntegerField(default=0)),
                ("start_date", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Invitation Pending"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Invitation Rejected"),
                            ("FAILED", "Failed"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("creator_completed_today", models.BooleanField(default=False)),
                ("partner_completed_today", models.BooleanField(default=False)),
                ("creator_verified_partner", models.BooleanField(default=False)),
                ("partner_verified_creator", models.BooleanField(default=False)),
                ("last_update_date", models.DateField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="joined_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="challange.challengetemplate",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="challengetemplate",
            name="reward_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="challange.item",
            ),
        ),
        migrations.CreateModel(
            name="UserItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("obtained_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="challange.item"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "item")},
            },
        ),
    ]
