# Generated by Django 5.1.2 on 2026-05-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challange", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="model_glb",
            field=models.FileField(blank=True, null=True, upload_to="models/items/"),
        ),
        migrations.AddField(
            model_name="item",
            name="model_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="External GLB URL (alternative to uploaded file)",
            ),
        ),
    ]
