# Generated by Django 5.1.2 on 2026-05-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challange", "0002_item_model_glb_item_model_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="anchor",
            field=models.CharField(
                choices=[
                    ("head", "Head"),
                    ("face", "Face"),
                    ("hand", "Hand"),
                    ("back", "Back"),
                    ("neck", "Neck"),
                    ("none", "None"),
                ],
                default="head",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="item_scale",
            field=models.FloatField(
                default=1.0, help_text="Render scale of the item on the avatar"
            ),
        ),
    ]
