# Generated by Django 5.1.2 on 2026-06-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challange", "0003_item_anchor_item_item_scale"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=60),
        ),
    ]
