# Generated by Django 5.1.2 on 2026-06-10 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challange", "0005_item_shop_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="useritem",
            options={"ordering": ["-obtained_at"]},
        ),
    ]
