# Generated by Django 5.1.2 on 2026-01-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("friends", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendship",
            name="last_interaction_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="friendship",
            name="streak",
            field=models.IntegerField(default=0),
        ),
    ]
