# Generated by Django 5.1.2 on 2025-11-27 20:38

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('habit_type', models.CharField(choices=[('time', 'Time-based'), ('count', 'Count-based')], max_length=10)),
                ('target_count', models.IntegerField(blank=True, null=True)),
                ('target_time', models.DurationField(blank=True, null=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('total_time', models.DurationField(blank=True, null=True)),
                ('streak', models.IntegerField(db_index=True, default=0)),
                ('completed_count', models.IntegerField(db_index=True, default=0)),
                ('last_completed_date', models.DateField(blank=True, db_index=True, null=True)),
                ('verified_count', models.IntegerField(default=0, help_text='Arkadaş onaylı tamamlanma sayısı.')),
                ('verification_streak', models.IntegerField(default=0)),
                ('last_proof_submission_date', models.DateField(blank=True, null=True)),
                ('last_reset_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], db_index=True, max_length=10)),
                ('custom_frequency_days', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-last_completed_date'],
            },
        ),
        migrations.CreateModel(
            name='HabitCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_at', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
