# Generated by Django 5.1.2 on 2025-11-27 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='habitcompletion',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='habits.habit'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'last_completed_date'], name='habits_habi_user_id_4470ac_idx'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['frequency', 'last_reset_date'], name='habits_habi_frequen_fbb6f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='habitcompletion',
            unique_together={('habit', 'completed_at')},
        ),
    ]
