# Generated by Django 5.1.2 on 2026-01-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="ai_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="habit",
            name="last_ai_verification_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
