# Generated by Django 5.1.2 on 2026-01-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_habit_ai_streak_habit_last_ai_verification_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="best_streak",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
