# Generated by Django 5.1.2 on 2026-01-23 23:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_habit_best_streak"),
    ]

    operations = [
        migrations.CreateModel(
            name="HabitHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("count", models.PositiveIntegerField(default=0)),
                ("total_time", models.DurationField(blank=True, null=True)),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="habits.habit",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("habit", "date")},
            },
        ),
    ]
