# Generated by Django 5.1.2 on 2026-01-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_habithistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="created_at",
            field=models.DateField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
