# Generated by Django 5.1.2 on 2026-01-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0006_habit_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="color",
            field=models.CharField(
                choices=[
                    ("green", "Green"),
                    ("yellow", "Yellow"),
                    ("purple", "Purple"),
                    ("orange", "Orange"),
                    ("pink", "Pink"),
                    ("blue", "Blue"),
                ],
                default="blue",
                max_length=10,
            ),
        ),
    ]
