# Generated by Django 5.1.2 on 2026-01-24 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challange", "0001_initial"),
        ("habits", "0007_habit_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="challenge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_habits",
                to="challange.challenge",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="is_challenge_habit",
            field=models.BooleanField(default=False),
        ),
    ]
