# Generated by Django 5.1.2 on 2026-02-25 01:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0008_habit_challenge_habit_is_challenge_habit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="verification_streak",
            field=models.IntegerField(
                default=0, help_text="Consecutive days of friend-verified completions."
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="verified_count",
            field=models.IntegerField(
                default=0, help_text="Friend-verified completion count."
            ),
        ),
        migrations.CreateModel(
            name="HabitVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("verified_date", models.DateField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to="habits.habit",
                    ),
                ),
            ],
            options={
                "ordering": ["-verified_date"],
                "unique_together": {("habit", "verified_date")},
            },
        ),
    ]
