# Generated by Django 5.1.2 on 2026-05-30 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0009_alter_habit_verification_streak_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="ai_streak",
        ),
        migrations.RemoveField(
            model_name="habit",
            name="last_ai_verification_date",
        ),
    ]
