# Generated by Django 5.1.2 on 2026-05-30 13:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0010_remove_habit_ai_streak_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HabitTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "icon",
                    models.CharField(
                        default="✅", help_text="Emoji, e.g. 💧", max_length=8
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("health", "Health"),
                            ("fitness", "Fitness"),
                            ("mind", "Mind"),
                            ("productivity", "Productivity"),
                            ("lifestyle", "Lifestyle"),
                        ],
                        default="lifestyle",
                        max_length=20,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("green", "Green"),
                            ("yellow", "Yellow"),
                            ("purple", "Purple"),
                            ("orange", "Orange"),
                            ("pink", "Pink"),
                            ("blue", "Blue"),
                        ],
                        default="blue",
                        max_length=10,
                    ),
                ),
                (
                    "habit_type",
                    models.CharField(
                        choices=[("time", "Time-based"), ("count", "Count-based")],
                        default="count",
                        max_length=10,
                    ),
                ),
                (
                    "default_target_count",
                    models.IntegerField(blank=True, default=1, null=True),
                ),
                (
                    "default_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("custom", "Custom"),
                        ],
                        default="daily",
                        max_length=10,
                    ),
                ),
                (
                    "reminder_copy",
                    models.CharField(
                        default="Don't forget your check today!", max_length=200
                    ),
                ),
                ("reminder_time", models.TimeField(blank=True, null=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="habit",
            name="icon",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Emoji shown for this habit, e.g. 💧",
                max_length=8,
            ),
        ),
    ]
