# Generated by Django 5.1.2 on 2026-06-02 15:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_alter_chatmessage_sender"),
        ("habits", "0013_habitgroup_habitconnection_habitgroupmember"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="habitconnection",
            name="pre_recovery_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="habitconnection",
            name="recovery_eligible_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="habitgroup",
            name="adaptation_mode_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="habitgroup",
            name="adaptation_mode_until",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="habitgroup",
            name="pre_recovery_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="habitgroup",
            name="recovery_eligible_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="habitgroupmember",
            name="pending_leave_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="GroupReserve",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("can_withdraw", models.BooleanField(default=True)),
                ("used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reserves",
                        to="chat.conversation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_reserves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoomFreezeUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="freeze_usages",
                        to="chat.conversation",
                    ),
                ),
            ],
            options={
                "unique_together": {("conversation", "date")},
            },
        ),
    ]
