# Generated by Django 5.1.2 on 2026-06-10 01:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_live_room_metadata"),
        ("habits", "0011_habittemplate_habit_icon"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="chat_chatme_convers_c2caf0_idx",
            ),
        ),
    ]
